In [6]:
import numpy as np

In [3]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [4]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [9]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [10]:
a.shape

(3, 2, 3)

In [13]:
a = np.array(3)
a, a.shape

(array(3), ())

In [14]:
a = np.array([1, 3, 5, 7, 9])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [15]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [16]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [17]:
a = np.array([1, 3, 5, 7, 9])
a.size

5

In [18]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

In [19]:
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [20]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5


In [21]:
myArr

array([10, 56, 77, 23, 44])

In [1]:
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [7]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원 = {myArr2.ndim}, 구조 = {myArr2.shape}, 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}')

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원 = 2, 구조 = (3, 3), 구조타입 = <class 'tuple'>, size = 9


In [8]:
myList21 = [[1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [9]:
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [10]:
listA = [10, 30, 50]
listB = [1, 2, 3]

In [11]:
print(listA + listB)

[10, 30, 50, 1, 2, 3]


In [12]:
print(listA + 2)

TypeError: can only concatenate list (not "int") to list

In [13]:
print(listA * 2)

[10, 30, 50, 10, 30, 50]


In [14]:
print(listA * listB)

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
arrA = np.array([1, 2, 3])

In [16]:
print(arrA + 2)

[3 4 5]


In [17]:
print(arrA * 2)

[2 4 6]


In [18]:
arrB = np.array([4,5,6])

In [19]:
print(arrA + arrB)

[5 7 9]


In [20]:
print(arrA * arrB)

[ 4 10 18]


In [21]:
print(arrA / arrB)

[0.25 0.4  0.5 ]


In [22]:
print(arrA // arrB)
print(arrA % arrB)

[0 0 0]
[1 2 3]


In [23]:
myList_c = ['안녕', 100, 3.14, True, False]
print(myList_c)

['안녕', 100, 3.14, True, False]


In [24]:
myArr_c = np.array(myList_c)
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [25]:
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype)

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64
